---
version: '2'

services:
    mock:
        container_name: starterkit-mock
        build:
            context: ./apps/mockserver/src
            dockerfile: ./Dockerfile
        volumes:
            - ./apps/mockserver/src/api:/app/api
            - ./apps/mockserver/src/assets:/app/assets
            - ./apps/mockserver/src/presets:/app/presets
            - ./ssl:/ssl
        ports:
            - '3999:3999'
            - '4000:4000'
            - '443:443'
